# ****IMPORT LIBRARY****

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# ****READ THE DATASET****

In [2]:
df=pd.read_csv("/kaggle/input/datasets/architsharma01/loan-approval-prediction-dataset/loan_approval_dataset.csv")

# *CHECK THE TOP 5 ROWS***

In [3]:
df.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,4,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

# **CHECK THE DATA SHAPE**

In [4]:
df.shape

(4269, 13)

# **EXTARCT INFOMATION ABOUT EACH COLUMN**

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4269 entries, 0 to 4268
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   loan_id                    4269 non-null   int64
 1    no_of_dependents          4269 non-null   int64
 2    education                 4269 non-null   object
 3    self_employed             4269 non-null   object
 4    income_annum              4269 non-null   int64
 5    loan_amount               4269 non-null   int64
 6    loan_term                 4269 non-null   int64
 7    cibil_score               4269 non-null   int64
 8    residential_assets_value  4269 non-null   int64
 9    commercial_assets_value   4269 non-null   int64
 10   luxury_assets_value       4269 non-null   int64
 11   bank_asset_value          4269 non-null   int64
 12   loan_status               4269 non-null   object
dtypes: int64(10), object(3)
memory usage: 433.7+ KB

**CHECK DATSET HAVE NULL VALUE**

In [6]:
df.isnull().sum()

loan_id                      0
 no_of_dependents            0
 education                   0
 self_employed               0
 income_annum                0
 loan_amount                 0
 loan_term                   0
 cibil_score                 0
 residential_assets_value    0
 commercial_assets_value     0
 luxury_assets_value         0
 bank_asset_value            0
 loan_status                 0
dtype: int64

**REALTION WITH EACH COLUMN**

In [7]:
df.describe()

,loan_id,no_of_dependents,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value
count,4269.000000,4269.000000,4.269000e+03,4.269000e+03,4269.000000,4269.000000,4.269000e+03,4.269000e+03,4.269000e+03,4.269000e+03
mean,2135.000000,2.498712,5.059124e+06,1.513345e+07,10.900445,599.936051,7.472617e+06,4.973155e+06,1.512631e+07,4.976692e+06
std,1232.498479,1.695910,2.806840e+06,9.043363e+06,5.709187,172.430401,6.503637e+06,4.388966e+06,9.103754e+06,3.250185e+06
min,1.000000,0.000000,2.000000e+05,3.000000e+05,2.000000,300.000000,-1.000000e+05,0.000000e+00,3.000000e+05,0.000000e+00
25%,1068.000000,1.000000,2.700000e+06,7.700000e+06,6.000000,453.000000,2.200000e+06,1.300000e+06,7.500000e+06,2.300000e+06
50%,2135.000000,3.000000,5.100000e+06,1.450000e+07,10.000000,600.000000,5.600000e+06,3.700000e+06,1.460000e+07,4.600000e+06
75%,3202.000000,4.000000,7.500000e+06,2.150000e+07,16.000000,748.000000,1.130000e+07,7.600000e+06,2.170000e+07,7.100000e+06
max,4269.000000,5.000000,9.900000e+06,3.950000e+07,20.000000,900.000000,2.910000e+07,1.940000e+07,3.920000e+07,1.470000e+07

In [8]:
df[" education"].unique()

array([' Graduate', ' Not Graduate'], dtype=object)

Here, its classification problem

# **First convert categorical data to numerical use Ordinal encoding**

In [9]:
from sklearn.preprocessing import OrdinalEncoder

encode1=OrdinalEncoder(categories=[[" Graduate"," Not Graduate"]])
encode2=OrdinalEncoder(categories=[[" Yes"," No"]])

In [10]:
df[["Encode_education"]]=encode1.fit_transform(df[[" education"]])
df[["Encode_employed"]]=encode2.fit_transform(df[[" self_employed"]])

In [11]:
df.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status,Encode_education,Encode_employed
0,1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved,0.0,1.0
1,2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected,1.0,0.0
2,3,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected,0.0,1.0
3,4,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected,0.0,1.0
4,5,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected,1.0,0.0

In [12]:
df.drop(columns=[" education"," self_employed"],inplace=True)

# **Remove categorical input part**

In [13]:
df.head()

,loan_id,no_of_dependents,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status,Encode_education,Encode_employed
0,1,2,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved,0.0,1.0
1,2,0,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected,1.0,0.0
2,3,3,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected,0.0,1.0
3,4,3,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected,0.0,1.0
4,5,5,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected,1.0,0.0

# **Split the data**

In [14]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(df.drop(columns=[" loan_status"]),df[" loan_status"],test_size=0.2,random_state=42)

In [15]:
x_train.head()

,loan_id,no_of_dependents,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,Encode_education,Encode_employed
1675,1676,5,7900000,29900000,6,568,5800000,13900000,15900000,8700000,1.0,1.0
1164,1165,0,9600000,34000000,12,710,23800000,10300000,38100000,7800000,1.0,0.0
192,193,1,800000,2900000,8,682,2200000,1100000,2900000,700000,0.0,1.0
910,911,2,4900000,13100000,18,754,8200000,3300000,16500000,7200000,0.0,0.0
567,568,5,3000000,11100000,12,441,8500000,2500000,7300000,2000000,0.0,0.0

# **Now, Convert categorical y_train column with label encoder**

In [16]:
from sklearn.preprocessing import LabelEncoder

In [17]:
le=LabelEncoder()

In [18]:
y_train=le.fit_transform(y_train)

In [19]:
y_test=le.transform(y_test)

In [20]:
y_train

array([0, 0, 0, ..., 1, 1, 0])

# **Import All features**

In [21]:
from sklearn.pipeline import make_pipeline
from sklearn.feature_selection import SelectKBest,f_classif
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier

In [22]:
trf1=SelectKBest(score_func=f_classif,k=10)

In [23]:
trf2=DecisionTreeClassifier()

In [24]:
pipe=make_pipeline(trf1,trf2)

In [25]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('selectkbest', SelectKBest()),
                ('decisiontreeclassifier', DecisionTreeClassifier())])

In [26]:
y_predict=pipe.predict(x_test)

In [27]:
accuracy_score(y_predict,y_test)

0.9754098360655737

# **Now Apply cross validation**

In [28]:
cross_val_score(pipe,x_train,y_train,cv=5,scoring='precision').mean()

np.float64(0.956625629782278)

In [29]:
cross_val_score(pipe,x_train,y_train,cv=5,scoring='recall').mean()

np.float64(0.962934362934363)

In [30]:
cross_val_score(pipe,x_train,y_train,cv=5,scoring='f1').mean()

np.float64(0.9562526584166579)

# **Use Random forest calssifier**

In [31]:
from sklearn.ensemble import RandomForestClassifier

In [32]:
trf3=RandomForestClassifier()

In [33]:
pipe=make_pipeline(trf1,trf3)
pipe.fit(x_train,y_train)
y_predict=pipe.predict(x_test)

In [34]:
accuracy_score(y_predict,y_test)

0.9765807962529274

In [35]:
cross_val_score(pipe,x_train,y_train,cv=5,scoring='precision').mean()

np.float64(0.965810576424591)

--------------END------------------